#!/bin/python3

""" for the 0-hello_route """
""" the route app must be listening on '0.0.0.0' """

from flask import Flask

    app = Flask (__name__)

    @app.route('/', strict_slashes=False)
    def get(self):

        return {"HELLO HBNB!"}
    if __name__ == '__main__'
    app.run(host = '0.0.0.0', port = '5000')
